### ISSUE TITLE
Unexpected Response : UNKNOWN_ERROR_NAN

### ISSUE THREAD

**Issue by utsavtiwary04** [AgoraIO-Community/AgoraWebSDK-NG#58]
### Describe the bug
Spotted this error in console. Don't have specific steps to reproduce this yet.

**Channel**:    C709-L9bce

**UID**:    1001

Platform and Browser:    Chrome, Web

SDK Version:    Agora Web SDK NG
<img width="1153" alt="Screenshot 2020-08-07 at 16 16 12" src="https://user-images.githubusercontent.com/6642834/89638603-ba122980-d8c9-11ea-8dca-756e2fb88934.png">

**Comment by utsavtiwary04** [comment]
@disoul Could you please help here ? Thank you !

**Comment by disoul** [comment]
This error occurred because you have already called `setClientRole("host")` and you want to call it again before the last call has not been resolved. It should be better for SDK to ignore this error, we will remove this error in the next version.

For now, you can add a try-catch to ignore this error.

**Comment by utsavtiwary04** [comment]
Thanks @disoul . Appreciate it !

**Comment by disoul** [comment]
fixed in v4.1.0
